// <auto-generated />
using System;
using GestorIncidentesTI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorIncidentesTI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915024615_InicialSchema")]
    partial class InicialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorIncidentesTI.Models.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<int>("NivelAnterior")
                        .HasColumnType("int");

                    b.Property<int>("NivelNuevo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("GestorIncidentesTI.Models.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsignadoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteSla")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SlaIncumplido")
                        .HasColumnType("bit");

                    b.Property<string>("SolicitanteNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("GestorIncidentesTI.Models.SlaDefinicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HorasResolucion")
                        .HasColumnType("int");

                    b.Property<int>("HorasRespuesta")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<double>("UmbralEscalamiento")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SlaDefiniciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HorasResolucion = 4,
                            HorasRespuesta = 1,
                            Prioridad = 4,
                            UmbralEscalamiento = 0.69999999999999996
                        },
                        new
                        {
                            Id = 2,
                            HorasResolucion = 8,
                            HorasRespuesta = 2,
                            Prioridad = 3,
                            UmbralEscalamiento = 0.75
                        },
                        new
                        {
                            Id = 3,
                            HorasResolucion = 24,
                            HorasRespuesta = 4,
                            Prioridad = 2,
                            UmbralEscalamiento = 0.80000000000000004
                        },
                        new
                        {
                            Id = 4,
                            HorasResolucion = 72,
                            HorasRespuesta = 8,
                            Prioridad = 1,
                            UmbralEscalamiento = 0.84999999999999998
                        });
                });

            modelBuilder.Entity("GestorIncidentesTI.Models.HistorialEstado", b =>
                {
                    b.HasOne("GestorIncidentesTI.Models.Incidente", "Incidente")
                        .WithMany("Historial")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("GestorIncidentesTI.Models.Incidente", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
